apiVersion: apps/v1
kind: Deployment
metadata:
  name: fist-kubernetes-app  # App name 
spec:
  replicas: 2   #No of pods=2
  selector:
    matchLabels:
      app: fist-kubernetes-app
  template:
    metadata:
      labels:
        app: fist-kubernetes-app
    spec:
      containers:
      - name: fist-kubernetes-app
        image: flask-app:latest
        imagePullPolicy: Never #tell kubernete not to pull image for specific registiry(remote repo like dockerhub etc)
        #image: haseeb1511/flask-app:latest  # Incase we want to pull image from remote registry
        resources:
          limits:
            memory: "64Mi"
            cpu: "200m"  #200 mili core cpu to each node (single core 1/5 = 200m)
        ports:
        - containerPort: 5000

--- 
apiVersion: v1
kind: Service
metadata:
  name: fist-kubernetes-app
spec:
  selector:
    app: fist-kubernetes-app
  ports:
  - port: 8080
    targetPort: 5000



