
services:
  fastapi:
    build:
      context: .                               # directery root
      dockerfile: backend/Dockerfile.fastapi   #dockerfile path
    container_name: fastapi_service
    ports:
      - "8000:8000"
    env_file:
      - .env    #.env file
    networks:
      - app_network

  streamlit:
    build:
      context: .
      dockerfile: frontend/Dockerfile.streamlit

    container_name: streamlit_service
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - fastapi
    environment:
      - API_URL=http://fastapi:8000/predict   #url to hit make change according
    networks:
      - app_network

networks:
  app_network:
    driver: bridge




##====================== FOr local Testing instead of image
  #  build:
  #     context: ./backend
  #     dockerfile: Dockerfile.fastapi

